services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    env_file:
      - .env
    volumes:
      - ./config/jellyfin:/config
      - ./data/movies:/data/movies
      - ./data/tvshows:/data/tvshows
    ports:
      - 8096:8096
      - 8920:8920 # optional, https
      - 7359:7359/udp # optional, dlna
      - 1900:1900/udp # optional, ssdp
    restart: unless-stopped

#  sonarr:
#    image: linuxserver/sonarr
#    container_name: sonarr
#    volumes:
#      - ./config:/config
#      - ./data/tvshows:/tv
#      - ./data/downloads:/downloads
#    ports:
#      - 8989:8989
#    restart: unless-stopped
